/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Conexion.ConexionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class Inicio_Sesion extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_Sesion
     */
    public Inicio_Sesion() {
        initComponents();
        initSesionBD();
        this.setLocationRelativeTo(null);
    }
    
    private void initSesionBD(){
           ConexionBD conect= new ConexionBD(); 
        try {
            Connection con = conect.conectar();
            Statement stmt=con.createStatement();  
            boolean rs=stmt.execute("SET GLOBAL time_zone = '-5:00'");
            boolean rs2=stmt.execute("SET time_zone = '-5:00'");
        } catch (SQLException ex) {
            Logger.getLogger(Inicio_Sesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        Iniciar_Sesion = new javax.swing.JButton();
        Olvide_Contrasenia = new javax.swing.JButton();
        Registrarse = new javax.swing.JButton();
        Usuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContrasenia = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("  IKEA GAMES");
        jLabelTitulo.setName("IKEA GAMES"); // NOI18N
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 280, 50));

        Iniciar_Sesion.setBackground(new java.awt.Color(0, 0, 51));
        Iniciar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio de sesion.png"))); // NOI18N
        Iniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_SesionActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 210, -1));

        Olvide_Contrasenia.setBackground(new java.awt.Color(0, 0, 51));
        Olvide_Contrasenia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Olvide_Contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        Olvide_Contrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Olvide contraseña.png"))); // NOI18N
        Olvide_Contrasenia.setText("Olvidaste Contraseña");
        Olvide_Contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Olvide_ContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(Olvide_Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        Registrarse.setBackground(new java.awt.Color(0, 0, 51));
        Registrarse.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Registrarse.setForeground(new java.awt.Color(255, 255, 255));
        Registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrarse.png"))); // NOI18N
        Registrarse.setText("Registrate");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 210, -1));

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(0, 0, 51));
        jTextFieldUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));

        jLabelContrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contraseña.png"))); // NOI18N
        getContentPane().add(jLabelContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jPassword.setBackground(new java.awt.Color(0, 0, 51));
        jPassword.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_1.jpg"))); // NOI18N
        jLabel1.setText("jLabelFondo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 406, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Iniciar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_SesionActionPerformed
                try{ 
            
            System.out.println(jTextFieldUsuario.getText());
           ConexionBD conect= new ConexionBD(); 
           Connection con = conect.conectar();
           Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from arquitectura.usuarios where user = '"+jTextFieldUsuario.getText()+"'"); 
            while(rs.next())  {
                        System.out.println(rs.getString(1)+"  "+rs.getString(2)+" ");
            if (rs.getString(1).equals(jTextFieldUsuario.getText())&&rs.getString(2).equals(jPassword.getText())){
                System.out.println("usuario valido");
                Panel_Central obj=new Panel_Central();
                obj.setVisible(true);
            }
            else{System.out.println("usuario o contraseña invalido");
            JOptionPane.showMessageDialog(null, "Usuario o contraseña invalido", "Error", JOptionPane.WARNING_MESSAGE);
                Inicio_Sesion obj=new Inicio_Sesion();
                obj.setVisible(true);
            }
            }

            con.close();  
            }catch(Exception e){ System.out.println(e);}
    }//GEN-LAST:event_Iniciar_SesionActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        Registro obj=new Registro();
        obj.setVisible(true);
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void Olvide_ContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Olvide_ContraseniaActionPerformed
        Olvide_Contraseña obj=new Olvide_Contraseña();
        obj.setVisible(true);
    }//GEN-LAST:event_Olvide_ContraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar_Sesion;
    private javax.swing.JButton Olvide_Contrasenia;
    private javax.swing.JButton Registrarse;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
