/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Juego_PingPong.Ventana;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class Juegos1 extends javax.swing.JFrame {

    /**
     * Creates new form Juegos1
     */
    public Juegos1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jButtonJ1 = new javax.swing.JButton();
        jButtonJ2 = new javax.swing.JButton();
        jButtonJ3 = new javax.swing.JButton();
        jButtonJ4 = new javax.swing.JButton();
        jButtonJ5 = new javax.swing.JButton();
        jButtonJ6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Juegos1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Tenemos Estos Juegos");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jButtonJ1.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJ1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonJ1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ping-pong.png"))); // NOI18N
        jButtonJ1.setText("Ping Pong");
        jButtonJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, 70));

        jButtonJ2.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJ2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonJ2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ2.setText("Juego #2");
        jButtonJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 130, 70));

        jButtonJ3.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJ3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonJ3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ3.setText("Juego #3");
        jButtonJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 130, 70));

        jButtonJ4.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJ4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonJ4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ4.setText("Juego #4");
        jButtonJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 130, 70));

        jButtonJ5.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJ5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonJ5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ5.setText("Juego #5");
        jButtonJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 130, 70));

        jButtonJ6.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJ6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonJ6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ6.setText("Juego #6");
        jButtonJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 130, 70));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 400, -1));

        Juegos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_1.jpg"))); // NOI18N
        getContentPane().add(Juegos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ2ActionPerformed
        JOptionPane.showMessageDialog(null, "Juego No Disponible", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonJ2ActionPerformed

    private void jButtonJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ3ActionPerformed
        JOptionPane.showMessageDialog(null, "Juego No Disponible", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonJ3ActionPerformed

    private void jButtonJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ4ActionPerformed
        JOptionPane.showMessageDialog(null, "Juego No Disponible", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonJ4ActionPerformed

    private void jButtonJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ5ActionPerformed
        JOptionPane.showMessageDialog(null, "Juego No Disponible", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonJ5ActionPerformed

    private void jButtonJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ6ActionPerformed
        JOptionPane.showMessageDialog(null, "Juego No Disponible", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonJ6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Panel_Central obj=new Panel_Central();
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ1ActionPerformed

        Ventana ventana = new Ventana();
        ventana.setVisible(true);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

 // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJ1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juegos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juegos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juegos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juegos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juegos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Juegos1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonJ1;
    private javax.swing.JButton jButtonJ2;
    private javax.swing.JButton jButtonJ3;
    private javax.swing.JButton jButtonJ4;
    private javax.swing.JButton jButtonJ5;
    private javax.swing.JButton jButtonJ6;
    // End of variables declaration//GEN-END:variables
}
