/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Conexion.ConexionBD;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class Olvide_Contraseña extends javax.swing.JFrame {

    /**
     * Creates new form Olvide_Contraseña
     */
    public Olvide_Contraseña() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOlvido_Contraseña = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasenia1 = new javax.swing.JLabel();
        jLabelConfirmacionContrasnia = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPassword1 = new javax.swing.JPasswordField();
        jPassword2 = new javax.swing.JPasswordField();
        jButtonListo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelContrasenia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOlvido_Contraseña.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabelOlvido_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOlvido_Contraseña.setText("Olvidaste Tu Contraseña");
        getContentPane().add(jLabelOlvido_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabelContrasenia1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelContrasenia1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContrasenia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contraseña.png"))); // NOI18N
        jLabelContrasenia1.setText("Nueva Contraseña:");
        getContentPane().add(jLabelContrasenia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabelConfirmacionContrasnia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelConfirmacionContrasnia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirmacionContrasnia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contraseña.png"))); // NOI18N
        jLabelConfirmacionContrasnia.setText("Confirma la Contraseña:");
        getContentPane().add(jLabelConfirmacionContrasnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(0, 0, 51));
        jTextFieldUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 240, 30));

        jPassword1.setBackground(new java.awt.Color(0, 0, 51));
        jPassword1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPassword1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 240, 30));

        jPassword2.setBackground(new java.awt.Color(0, 0, 51));
        jPassword2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPassword2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 240, 30));

        jButtonListo.setBackground(new java.awt.Color(0, 0, 51));
        jButtonListo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonListo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listo.png"))); // NOI18N
        jButtonListo.setText("Listo");
        jButtonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jLabelContrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_1.jpg"))); // NOI18N
        getContentPane().add(jLabelContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 521, 494));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Inicio_Sesion obj=new Inicio_Sesion();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListoActionPerformed
      System.out.println("jPasswordField1:"+jPassword1.getText());
      System.out.println("jPasswordField2:"+jPassword2.getText());
      System.out.println("jTextField1:"+jTextFieldUsuario.getText());
        if(jPassword1.getText().equals(jPassword2.getText())){
            
                    try {
            System.out.println(jTextFieldUsuario.getText());
            ConexionBD conect= new ConexionBD();
            Connection con = conect.conectar();
            Statement stmt=con.createStatement();
            boolean rs=stmt.execute("update arquitectura.usuarios set contrasenia = '"+jPassword2.getText()+"' where user = '"+jTextFieldUsuario.getText()+"'");   
            if(!rs){
                this.setVisible(false);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "No se pudo combiar contraseña", "Error", JOptionPane.WARNING_MESSAGE);
                Olvide_Contraseña obj=new Olvide_Contraseña();
                obj.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Olvide_Contraseña.class.getName()).log(Level.SEVERE, null, ex);
        }

              }
        else{
                JOptionPane.showMessageDialog(null, "Contraseña invalido", "Error", JOptionPane.WARNING_MESSAGE);
                Olvide_Contraseña obj=new Olvide_Contraseña();
                obj.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Olvide_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Olvide_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Olvide_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Olvide_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Olvide_Contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonListo;
    private javax.swing.JLabel jLabelConfirmacionContrasnia;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelContrasenia1;
    private javax.swing.JLabel jLabelOlvido_Contraseña;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JPasswordField jPassword2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
