/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Ivan
 */
public class PerfilR extends javax.swing.JFrame {

    /**
     * Creates new form PerfilR
     */
    public PerfilR() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelJuegos = new javax.swing.JLabel();
        jButtonVolver1 = new javax.swing.JButton();
        jButtonJuegos = new javax.swing.JButton();
        Perfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar sesion.png"))); // NOI18N
        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        jLabelJuegos.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabelJuegos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJuegos.setText("Esto Has Jugado");
        getContentPane().add(jLabelJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 300, 50));

        jButtonVolver1.setBackground(new java.awt.Color(0, 0, 51));
        jButtonVolver1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonVolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        jButtonVolver1.setText("Volver");
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jButtonJuegos.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJuegos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonJuegos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJuegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Juegos.png"))); // NOI18N
        jButtonJuegos.setText("Juegos");
        jButtonJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJuegosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, 40));

        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_1.jpg"))); // NOI18N
        getContentPane().add(Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 721, 501));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio_Sesion obj=new Inicio_Sesion();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        Panel_Central obj=new Panel_Central();
        obj.setVisible(true);
    }//GEN-LAST:event_jButtonVolver1ActionPerformed

    private void jButtonJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJuegosActionPerformed
        Juegos1 obj=new Juegos1();
        obj.setVisible(true);
    }//GEN-LAST:event_jButtonJuegosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Perfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonJuegos;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabelJuegos;
    // End of variables declaration//GEN-END:variables
}
