/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Conexion_BD.ConexionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegistrarse = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelUsiario = new javax.swing.JLabel();
        jLabelContrasenia = new javax.swing.JLabel();
        jLabelConfirmacion = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jPassword1 = new javax.swing.JPasswordField();
        jPassword2 = new javax.swing.JPasswordField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistrarse.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabelRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarse.setText("Registrarse");
        getContentPane().add(jLabelRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 260, 70));

        jLabelNombre.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabelApellido.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellidos:");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 20));

        jLabelUsiario.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabelUsiario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsiario.setText("Usuario:");
        getContentPane().add(jLabelUsiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabelContrasenia.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabelContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContrasenia.setText("Contraseña:");
        getContentPane().add(jLabelContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabelConfirmacion.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabelConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirmacion.setText("Confirmar contraseña:");
        getContentPane().add(jLabelConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 30));

        jLabelCorreo.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("correo:");
        getContentPane().add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 60, 30));

        jPassword1.setBackground(new java.awt.Color(0, 0, 51));
        jPassword1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 270, 30));

        jPassword2.setBackground(new java.awt.Color(0, 0, 51));
        jPassword2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPassword2.setForeground(new java.awt.Color(255, 255, 255));
        jPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 270, 30));

        jTextFieldNombre.setBackground(new java.awt.Color(0, 0, 51));
        jTextFieldNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 270, -1));

        jTextFieldApellido.setBackground(new java.awt.Color(0, 0, 51));
        jTextFieldApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 270, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(0, 0, 51));
        jTextFieldUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 270, -1));

        jTextFieldCorreo.setBackground(new java.awt.Color(0, 0, 51));
        jTextFieldCorreo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextFieldCorreo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 270, -1));

        Registrar.setBackground(new java.awt.Color(0, 0, 51));
        Registrar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro.png"))); // NOI18N
        Registrar.setText("Registrame");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jLabelRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_1.jpg"))); // NOI18N
        getContentPane().add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 525, 497));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword1ActionPerformed

    private void jPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio_Sesion obj=new Inicio_Sesion();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        System.out.println("jTextField3:"+jTextFieldUsuario.getText());
        System.out.println("jTextField2:"+jPassword1.getText());
        System.out.println("jTextField4:"+jTextFieldNombre.getText());
        System.out.println("jTextField7:"+jTextFieldApellido.getText());
        System.out.println("jPasswordField1:"+jTextFieldCorreo.getText());
        
        if(jPassword1.getText().equals(jPassword2.getText())){  
            try {
            ConexionBD conect= new ConexionBD();
            Connection con = conect.conectar();
            Statement stmt=con.createStatement();
            ResultSet rd=stmt.executeQuery("select * from arquitectura.usuarios where user = '"+jTextFieldUsuario.getText()+"'");
            if(rd.next()==false){
            boolean rs=stmt.execute("INSERT INTO `arquitectura`.`usuarios`\n" +
                                    "(`user`,\n" +
                                    "`contrasenia`,\n" +
                                    "`nombre`,\n" +
                                    "`apellido`,\n" +
                                    "`correo`)\n" +
                                    "VALUES\n" +
                                    "('"+jTextFieldUsuario.getText()+"',\n" +
                                    "'"+jPassword1.getText()+"',\n" +
                                    "'"+jTextFieldNombre.getText()+"',\n" +
                                    "'"+jTextFieldApellido.getText()+"',\n" +
                                    "'"+jTextFieldCorreo.getText()+"'\n" +
                                    ")");
             if(!rs){
                this.setVisible(false);
                this.dispose();    
            }
            else{
                JOptionPane.showMessageDialog(null, "No se pudo combiar contraseña", "Error", JOptionPane.WARNING_MESSAGE);
                Registro obj=new Registro();
                obj.setVisible(true);
            }           
            
            }
            else {
            JOptionPane.showMessageDialog(null, "Usuario Ya Existe", "Error", JOptionPane.WARNING_MESSAGE);
            Registro obj=new Registro();
            obj.setVisible(true);
            }

             
            Inicio_Sesion obj=new Inicio_Sesion();
            obj.setVisible(true);
            dispose();//        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

        else{
               JOptionPane.showMessageDialog(null, "Las Contraseñas no coinsiden", "Error", JOptionPane.WARNING_MESSAGE);
                Registro obj=new Registro();
                obj.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelConfirmacion;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRegistrarse;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelUsiario;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JPasswordField jPassword2;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
